from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    EMPTY_FILE = "EMPTY_FILE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    CORRUPTED_EXCEL_FILE = "CORRUPTED_EXCEL_FILE"
    MISSING_REQUIRED_COLUMNS = "MISSING_REQUIRED_COLUMNS"
    INVALID_EXCEL_DATA = "INVALID_EXCEL_DATA"

    NETWORK_ERROR = "NETWORK_ERROR"
    EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    FRED_SERVICE_ERROR = "FRED_SERVICE_ERROR"
    MARKET_DATA_ERROR = "MARKET_DATA_ERROR"

    NO_NEW_DATA = "NO_NEW_DATA"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    ENDPOINT_NOT_FOUND = "ENDPOINT_NOT_FOUND"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"